---
- hosts: all
  become: true
  vars:
    vg_name: centos_centos-ks 
    existing_devices: /dev/sda2
    new_device: /dev/sdb
    new_lv_name: docker
    docker_data_dir_name: docker
    docker_data_dir_parent: /var/lib
    tmp_data_folder: /tmp/_docker

  tasks:
    - name: Compute full path docker data
      set_fact:
        _docker_data_dir: "{{ docker_data_dir_parent }}/{{ docker_data_dir_name }}"
    
    - debug:
        msg: "_docker_data_dir: {{ _docker_data_dir }}"

    - name: Stop kubelet
      systemd:
        name: kubelet
        state: stopped

    - name: Stop docker
      systemd:
        name: docker
        state: stopped
        
    - name: extend volume group
      lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ existing_devices }},{{ new_device }}"

    - name: Create a logical volume the size of all remaining space in the volume group
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ new_lv_name }}"
        size: 100%FREE

    - name: Create an xfs filesystem on new volume
      filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name}}/{{ new_lv_name }}"
    
    - name: Ensure docker folder exists
      file:
        path: "{{ _docker_data_dir }}"
        state: directory

    - name: Mount new volume at docker data 
      mount:
        path: "{{ _docker_data_dir }}"
        src: "/dev/{{ vg_name}}/{{ new_lv_name }}"
        fstype: xfs
        state: mounted
          
    - name: Start docker
      systemd:
        name: docker
        state: restarted
        enabled: yes  

    - name: Start kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes  
    