---
- hosts: all
  become: true
  vars:
    vg_name: centos_centos-ks 
    lv_name: root 
    vg_devices: "/dev/sda2,/dev/sdb"
    
  tasks:
    - name: Create/Extend volume group
      lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ vg_devices }}"
      register: volume_group_result

    - name: Show result
      debug:
        msg: "{{ volume_group_result }}"

    - name: Extend the logical volume to consume all remaining space in the volume group
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: +100%FREE 
        resizefs: true
      when: volume_group_result.changed

    # - name: Create an xfs filesystem on new volume
    #   filesystem:
    #     fstype: xfs
    #     dev: "/dev/{{ vg_name}}/{{ new_lv_name }}"
    
    # - name: Ensure docker folder exists
    #   file:
    #     path: "{{ _docker_data_dir }}"
    #     state: directory

    # - name: Mount new volume at docker data 
    #   mount:
    #     path: "{{ _docker_data_dir }}"
    #     src: "/dev/{{ vg_name}}/{{ new_lv_name }}"
    #     fstype: xfs
    #     state: mounted
          
    # - name: Start docker
    #   systemd:
    #     name: docker
    #     state: restarted
    #     enabled: yes  

    # - name: Start kubelet
    #   systemd:
    #     name: kubelet
    #     state: started
    #     enabled: yes  
    