---
# tasks file for ansible_docker
- name: Install Docker prerequisites
  become: true
  yum:
    state: present
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Enable stable Docker repository
  become: true
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: Install Docker packages
  become: true
  yum:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start docker service
  become: true
  service:
    name: docker
    state: started
    enabled: yes
